-- 오랜 기간 보호한 동물(2)
SELECT I.ANIMAL_ID, I.NAME FROM
(SELECT I.ANIMAL_ID, I.NAME 
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O 
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TO_DATE(O.DATETIME) - TO_DATE(I.DATETIME) DESC)I
WHERE ROWNUM <= 2;