-- 입양 시각 구하기(1)
SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) COUNT 
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') > 8 AND TO_CHAR(DATETIME, 'HH24') < 20
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24');