-- 입양 시각 구하기(2)
SELECT A.HOUR, COUNT(TO_CHAR(DATETIME, 'HH24')) AS COUNT
FROM ANIMAL_OUTS O 
RIGHT JOIN (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24)A
ON A.HOUR = TO_CHAR(DATETIME, 'HH24')
GROUP BY A.HOUR
ORDER BY A.HOUR;